spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    generate-ddl: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/preternoko?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Keyduck2021^^
    driver-class-name: com.mysql.cj.jdbc.Driver
